Initial data
network-science-lab/top-spreaders-dataset pull request #1
Opened 2024-06-08 20:55 UTC by mateuszStolarski

2024-06-10 08:09 UTC, adampirog reviewed
- I'm not sure if we should keep the `__main__.py` script if it's currently empty [1]
- It may be worth to add the `dvc+gdrive` requirement to the `pyprojet.toml` [2]

2024-06-10 15:42 UTC, anty-filidor requested changes

2024-06-10 15:42 UTC, anty-filidor commented on .dvc/.gitignore
> +/config.local
[3] please provide a manual of pulling the data from dvc (including authentication in google drive)

2024-06-10 15:42 UTC, anty-filidor commented on .dvc/config
> +    url = gdrive://0ACmD69K7LbU3Uk9PVA/dvc/ns_datasources
[3] The URL is inconsistent with the name of the repository. Honestly, I'd go with `ns-data-sources` (datasource is an incorrect word and replace `_` with `-`), but for sure I'd use the same name in a DVC storage and on GitHub

2024-06-10 15:42 UTC, anty-filidor commented on .dvcignore
> +# Add patterns of files dvc should ignore, which could improve
[1] do we need this file? It was created by DVC automatically, but since it's empty, then what's a purpose of keeping it (YAGNI)

2024-06-10 15:42 UTC, anty-filidor commented on .dvc/.gitignore
> +/tmp
[1] Again, I'm not a fan of having `.gitignore`s scattered all over the repo. That file has been created automatically, hence we should think if we really need it.

2024-06-10 15:42 UTC, anty-filidor commented on .dvc/.gitignore
> +/cache
[3] There is no file with required versions of libraries. Please add it.

2024-06-10 15:42 UTC, anty-filidor commented on ns_datasources/data/raw/single_layer_networks/twitch_de.dvc
> +outs:
[3] The last thing. This is a PR to `master`, and I see that you've used your template. But that template assumes the repository is an installable Python package, and I'm not convinced whether this project should have that form.

Will we keep dataset loaders here? If so, then presumably it can be shaped into a pip-installable package. Otherwise, I'd remove test stub, get rid of nesting data in an additional folder, etc. If so, then we will be probably forced to have a compatibility between Python environments across all repositories. And for instance, here is a potential problem: in my repository I'm using Python 3.10 which cannot be bumped. You're using Python 3.11 here (according to the template).

During our last call, I proposed to use this repository as a submodule in all projects which will in fact require it. That allows us to be flexible e.fg. w.r.t. Python's version. However, there is (as usual) a trade-off: we will in fact be flexible, but some code will be duplicated (e.g. loaders).

I think we should discuss it...

2024-06-10 15:42 UTC, anty-filidor commented on ns_datasources/data/raw/single_layer_networks/twitch_de.dvc
> +- md5: 23ebe541913b6d53fcd7bd494dcf3764.dir
[1] I've checked out the repo and it seems to work.

2024-06-10 15:47 UTC, anty-filidor commented
> * I'm not sure if we should keep the `__main__.py` script if it's currently empty [1]
> 
>     * It may be worth to add the `dvc+gdrive` requirement to the `pyprojet.toml` [2]

@adampirog --- I'm not a fan of sticking everything inside pyproject.toml which is supposed to contain only static data. That (if i recall correctly) will also not work with conda. However, there is a compromise --- you can add a reference to the requirements.txt inside a toml file, so that it will be compatible with conda and included where you intended. That should address the issue:
```
[tool.setuptools.dynamic]
dependencies = {file = [<path to requirements.txt>]}
```

2024-06-10 16:36 UTC, adampirog commented on ns_datasources/data/raw/single_layer_networks/twitch_de.dvc
> +outs:
I agree. I'm not sure about using our template here either.

2024-06-10 16:53 UTC, adampirog commented
@anty-filidor For me it's neat and concise to have everything needed for creating/installing a package in one file. I don't think there is a need to expand and complicate our repository structure, especially with smaller projects such as ours. Software deployment is not necessarily my area of expertise, but as far as I can tell, keeping requirements in pyproject.toml is pretty common, even in top-tier projects.

About your conda concerns - I'm not sure what you mean exactly. I'm using conda and it works just fine.

2024-06-10 17:36 UTC, mateuszStolarski commented
For other repositories, I would also prefer to have everything (related to the environment) in one place. If there are any problems with conda on Mac and pyproject.toml, we can discuss them on the call.

2024-06-11 12:41 UTC, anty-filidor approved these changes

2024-06-16 11:29 UTC, adampirog approved these changes

2024-06-17 09:29 UTC, merged