Add generation script
network-science-lab/top-spreaders-dataset pull request #6
Opened 2024-10-08 08:02 UTC by adampirog

Multilayer network generation scripts

@mateuszStolarski  please, review as well. I guess you can't put multiple reviewers on a private repo.

2024-10-08 19:14 UTC, anty-filidor requested changes

2024-10-08 19:14 UTC, anty-filidor commented on nsl_data_utils/misc/generate.py
> +        ml.evolution_er(n)
Correct me please if I'm mistaken, but it seems that in the current state of the repository, we can only generate ER networks. IMHO it's not enough

2024-10-08 19:18 UTC, adampirog commented on nsl_data_utils/misc/generate.py
> +        ml.evolution_er(n)
That's true, it's not much diversity. That's what I brought up at the meeting - the uunet lib has only ER and PA generation models.

2024-10-09 07:09 UTC, mateuszStolarski commented on nsl_data_utils/misc/generate.py
> +        ml.evolution_er(n)
I suggest to generate ER networks and run simulations on them and in the meantime we will find/implement watts_strogats, barabasi_albert and may be some other generation models for multilayer networks

2024-10-15 15:54 UTC, anty-filidor approved these changes

2024-10-15 16:49 UTC, mateuszStolarski approved these changes

2024-10-15 17:49 UTC, merged