Feature  synthetic dataset
network-science-lab/top-spreaders-dataset pull request #8
Opened 2024-10-25 08:58 UTC by anty-filidor

Added synthetic dataset, i.e. 100 ER and 100 PA networks with spreading potentials computed for their actors.

Updated loaders for networks and spreading potentials so that it's able to load that data with bulk option (please pay attention for that).

2024-10-25 11:11 UTC, mateuszStolarski requested changes

2024-10-25 11:11 UTC, mateuszStolarski commented on nsl_data_utils/loaders/net_loader.py
> +    for path in tqdm(paths,  desc="loading networks"):
(1)
```
nets_dict = {path.stem: nd.MultilayerNetwork.from_mpx(str(path)) for path in tqdm(paths,  desc="loading networks")}
```

2024-10-25 11:11 UTC, mateuszStolarski commented on nsl_data_utils/loaders/constants.py
> +ARTIFICIAL_ER = "artificial_er"  # a bunch of nets
(3) We should discuss whether to keep those networks in this way or maybe split them into train/eval (train_artificial_er, train_artificial_pa etc)

2024-10-25 11:11 UTC, mateuszStolarski commented on nsl_data_utils/loaders/net_loader.py
> +            return {
We have to validate whether those changes (covert_to_torch, load_network, load_sp) will work in the training repo, and if not, update the proper code there

2024-10-25 11:11 UTC, mateuszStolarski commented on nsl_data_utils/loaders/sp_loader.py
> +def _sort_csv_paths(csv_regex: str):
(1) `def _sort_csv_paths(csv_regex: str) -> dict[str, Path]:`

2024-10-25 11:11 UTC, mateuszStolarski commented on nsl_data_utils/loaders/sp_loader.py
> +    return sp_dict
(1)
```
return { 
  net_name: _get_sp(csv_paths) for net_name, csv_paths in _sort_csv_paths(f"{net_group_name}/*.csv").items()
}
```

2024-10-25 11:11 UTC, mateuszStolarski commented on nsl_data_utils/models/torch_model.py
> -        #     "Some nodes were activated against rules - only these with state 0 can be activated!"
(1) do we need this?

2024-10-25 12:16 UTC, anty-filidor commented on nsl_data_utils/models/torch_model.py
> -        #     "Some nodes were activated against rules - only these with state 0 can be activated!"
yes, we need that for debugging

2024-10-25 12:17 UTC, anty-filidor commented on nsl_data_utils/loaders/sp_loader.py
> +    return sp_dict
your version is tjust he same but makes more line splits which makes code less readible ;)

2024-10-25 12:18 UTC, anty-filidor commented on nsl_data_utils/loaders/sp_loader.py
> +def _sort_csv_paths(csv_regex: str):
thanks, I've applied your suggestion, but in fact its ` dict[str, list[Path]]`

2024-10-25 12:20 UTC, anty-filidor commented on nsl_data_utils/loaders/net_loader.py
> +            return {
Well, I've changed the interface, so it won't work out of the box in the trainer repo, and IMHO it's the next step after merging this PR :D

2024-10-25 12:21 UTC, anty-filidor commented on nsl_data_utils/loaders/constants.py
> +ARTIFICIAL_ER = "artificial_er"  # a bunch of nets
sure, we have to split these into subsets, but it's not a part of this basic loader since it's shared with simulator which won't use that feature. It's a work to be done in the trainer repo

2024-10-25 12:23 UTC, anty-filidor commented on nsl_data_utils/loaders/net_loader.py
> +    for path in tqdm(paths,  desc="loading networks"):
IMHO that's the same (maybe a bit faster since comprehensions are "in principle" faster), but will make code less reafible since its very very long expression ;)

2024-10-28 07:11 UTC, mateuszStolarski approved these changes

2024-10-28 08:50 UTC, adampirog approved these changes

2024-10-28 09:54 UTC, merged